

import MY_Classes.Func_Class;
import java.awt.Color;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;

import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hassan
 */
public class AddBook extends javax.swing.JFrame {

	/**
	 * Creates new form AddBook
	 */
	
	MY_Classes.Genre genre = new MY_Classes.Genre();
	MY_Classes.Func_Class func = new Func_Class();
	
	HashMap<String,Integer> genresmap = genre.getGenresMap();
	String imagePath ="";
	public AddBook() {
		initComponents();
		this.setLocationRelativeTo(this);
			Border p = BorderFactory.createMatteBorder(5, 5,5,5,new Color(73,94,87));
		jPanel_kekle.setBorder(p);
		filljcombowithgenres();
	   
	    
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel_kekle = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_ISBN = new javax.swing.JTextField();
        jTextField_adi = new javax.swing.JTextField();
        jTextField_yazar = new javax.swing.JTextField();
        jTextField_fyiay = new javax.swing.JTextField();
        jTextField_yayimci = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel_path = new javax.swing.JLabel();
        jLabel_photo = new javax.swing.JLabel();
        jButton_fotosec = new javax.swing.JButton();
        jButton_kitapekle = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jSpinner1 = new javax.swing.JSpinner();
        jButton_authorara = new javax.swing.JButton();
        jLabel_genid = new javax.swing.JLabel();
        jLabel_authid = new javax.swing.JLabel();
        jButton_kitapekle1 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jLabel16.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("FIYAT:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_kekle.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_kekle.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(73, 94, 87));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setText("KITAP EKLE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel1)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel2.setBackground(new java.awt.Color(73, 94, 87));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ISBN:");
        jLabel3.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ADI:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("YAZAR:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("TÜR:");

        jLabel10.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("MIKTAR:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("YAYIMCI:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("FİYAT:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("KITAP KAPAIGI:");

        jTextField_yazar.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("ALINDIğI TARIH");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("KITAP HAKKINDA:");

        jLabel_path.setText("Path");

        jLabel_photo.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_photo.setOpaque(true);

        jButton_fotosec.setText("FOTO SEC ");
        jButton_fotosec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fotosecActionPerformed(evt);
            }
        });

        jButton_kitapekle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_kitapekle.setText("KITAP EKLE");
        jButton_kitapekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_kitapekleActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(73, 94, 87));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });

        jButton_authorara.setText("Yazar DIGSTIR");
        jButton_authorara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_authoraraActionPerformed(evt);
            }
        });

        jLabel_genid.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_genid.setText("ID");

        jLabel_authid.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_authid.setText("ID");

        jButton_kitapekle1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_kitapekle1.setText("TEMIZLE");
        jButton_kitapekle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_kitapekle1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_kekleLayout = new javax.swing.GroupLayout(jPanel_kekle);
        jPanel_kekle.setLayout(jPanel_kekleLayout);
        jPanel_kekleLayout.setHorizontalGroup(
            jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_kekleLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(jPanel_kekleLayout.createSequentialGroup()
                .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_kekleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_kekleLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_adi, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(jTextField_ISBN)))
                            .addGroup(jPanel_kekleLayout.createSequentialGroup()
                                .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_kekleLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField_fyiay))
                                    .addGroup(jPanel_kekleLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_yazar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_kekleLayout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_kekleLayout.createSequentialGroup()
                                        .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_yayimci, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_kekleLayout.createSequentialGroup()
                                        .addComponent(jLabel_authid, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_authorara))
                                    .addComponent(jLabel_genid, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel_kekleLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_kekleLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_kitapekle, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)))
                .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addComponent(jLabel13)
                        .addGroup(jPanel_kekleLayout.createSequentialGroup()
                            .addComponent(jLabel_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton_fotosec)
                                .addComponent(jLabel_path, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_kekleLayout.createSequentialGroup()
                        .addComponent(jButton_kitapekle1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158)))
                .addGap(422, 422, 422))
        );
        jPanel_kekleLayout.setVerticalGroup(
            jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_kekleLayout.createSequentialGroup()
                .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_kekleLayout.createSequentialGroup()
                        .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_yazar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jButton_authorara)
                            .addComponent(jLabel_authid))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_genid)))
                    .addGroup(jPanel_kekleLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_kekleLayout.createSequentialGroup()
                        .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel_kekleLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel_path)
                                .addGap(34, 34, 34)
                                .addComponent(jButton_fotosec)
                                .addGap(24, 24, 24))
                            .addComponent(jLabel_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108))
                    .addGroup(jPanel_kekleLayout.createSequentialGroup()
                        .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField_yayimci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField_fyiay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(jPanel_kekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_kitapekle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_kitapekle1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_kekle, javax.swing.GroupLayout.PREFERRED_SIZE, 737, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_kekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_fotosecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fotosecActionPerformed
        // TODO add your handling code here:
		String path = func.selectImage();
		jLabel_path.setText(path);
		
		func.displayImage(jLabel_photo.getWidth(), jLabel_photo.getHeight(),null, path,jLabel_photo);
		
		imagePath = path;
    }//GEN-LAST:event_jButton_fotosecActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
	
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
		this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton_kitapekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_kitapekleActionPerformed
        // TODO add your handling code here:
		MY_Classes.Book book = new MY_Classes.Book();
		String isbn = jTextField_ISBN.getText();
		if(!verif())
		{
			JOptionPane.showMessageDialog(null,"ALANLARIN BOŞ BIRAKILMAZ","",1);
		}else if(book.isisbnexist(isbn))
		{
			JOptionPane.showMessageDialog(null,"bu kitap zaten eklenmiş","",1);
		}
		
		
		else{
			
		try {
				
				String name = jTextField_adi.getText();
				String publisher = jTextField_yayimci.getText();
				String about = jTextArea1.getText();
		
				Integer authorid = Integer.parseInt(jLabel_authid.getText());
				Integer genresid = Integer.parseInt(jLabel_genid.getText());
				Integer quantity = Integer.parseInt(jSpinner1.getValue().toString());
		
		
				Double price =Double.parseDouble(jTextField_fyiay.getText());
		
				SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
				
				String Daterc = dateformat.format(jDateChooser1.getDate());
				Path path = Paths.get(imagePath);
				byte[] img = Files.readAllBytes(path);
				
	            book.addbook(isbn, name, authorid,genresid,quantity,publisher,price,Daterc,about,img);
		} catch (IOException ex) {
			JOptionPane.showMessageDialog(null,"","",1);
		}catch (NumberFormatException ex) {
			Logger.getLogger(AddBook.class.getName()).log(Level.SEVERE, null, ex);
		}catch (NullPointerException ex) {
			Logger.getLogger(AddBook.class.getName()).log(Level.SEVERE, null, ex);
		}
				
		}
			
		
		
    }//GEN-LAST:event_jButton_kitapekleActionPerformed

    private void jButton_authoraraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_authoraraActionPerformed
        // TODO add your handling code here:
	AuthorsListForm authorlist = new AuthorsListForm();
	
	authorlist.setVisible(true);
		
		
		
    }//GEN-LAST:event_jButton_authoraraActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
		try{
		int genreId = genresmap.get(jComboBox.getSelectedItem().toString());
		jLabel_genid.setText(String.valueOf(genreId));
		}catch(Exception ex)
		{
			
		}
    }//GEN-LAST:event_jComboBoxActionPerformed

    private void jButton_kitapekle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_kitapekle1ActionPerformed
        // TODO add your handling code here:
		
		jTextArea1.setText("");
		jTextField1.setText("");
		jTextField_ISBN.setText("");
		jTextField_adi.setText("");
		jTextField_fyiay.setText("");
		jComboBox.setSelectedIndex(0);
		jTextField_yayimci.setText("");
		jTextField_yazar.setText("");
		jDateChooser1.setDate(new java.util.Date());
		jSpinner1.setValue(0);
		jLabel_authid.setText("ID");
		jLabel_genid.setText("ID");
		
		jLabel_photo.setIcon(null);
		jLabel_path.setText("foto path");
		
		
    }//GEN-LAST:event_jButton_kitapekle1ActionPerformed
	public static void DisplayAuthorData(int id,String fullname)
	{
		
		jTextField_yazar.setText(fullname);
		

		jLabel_authid.setText(String.valueOf(id));
		
		
	}
	public void filljcombowithgenres()
	{
		for(String genreName: genresmap.keySet()){
			jComboBox.addItem(genreName);
		}
	}
	public boolean verif()
	{
		if(jTextField_ISBN.getText().equals("")|| jTextField_adi.getText().equals("")||jTextField_yazar.getText().equals("")||
				jTextField_fyiay.getText().equals("")||jLabel_genid.getText().equals(""))
		{
			//JOptionPane.showConfirmDialog(null,"ALANLARIN BAZILARI BOŞ","",1);
			return false;
		}else
		{
		return true;	
		}
	}
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AddBook().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_authorara;
    private javax.swing.JButton jButton_fotosec;
    private javax.swing.JButton jButton_kitapekle;
    private javax.swing.JButton jButton_kitapekle1;
    private javax.swing.JComboBox<String> jComboBox;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private static javax.swing.JLabel jLabel_authid;
    private javax.swing.JLabel jLabel_genid;
    private javax.swing.JLabel jLabel_path;
    private javax.swing.JLabel jLabel_photo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_kekle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_ISBN;
    private javax.swing.JTextField jTextField_adi;
    private javax.swing.JTextField jTextField_fyiay;
    private javax.swing.JTextField jTextField_yayimci;
    private static javax.swing.JTextField jTextField_yazar;
    // End of variables declaration//GEN-END:variables
}
