
import MY_Classes.Func_Class;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hassan
 */
public class AddMemberForm extends javax.swing.JFrame {

	/**
	 * Creates new form AddMemberForm
	 */
	MY_Classes.Members mem = new MY_Classes.Members();
	String imagePath =null;
	public AddMemberForm() {
		initComponents();
		this.setLocationRelativeTo(this);
		MY_Classes.Func_Class fun = new Func_Class();
		fun.displayImage(75,50,null,"/My_Images/mem.png/", jLabel_mem_tit);
		
		Border p = BorderFactory.createMatteBorder(5,5,5,5, new Color(153,204,255));
		jPanel__.setBorder(p);
		
		jLabel_teleh.setVisible(false);
		jLabel_soyh.setVisible(false);
		jLabel_emailh.setVisible(false);
		jLabel_adih.setVisible(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel__ = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_mem_tit = new javax.swing.JLabel();
        jLabel_adi = new javax.swing.JLabel();
        jTextField_adi = new javax.swing.JTextField();
        jLabel_adih = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_teleh = new javax.swing.JLabel();
        jLabel_soyh = new javax.swing.JLabel();
        jLabel_emailh = new javax.swing.JLabel();
        jTextField_tele = new javax.swing.JTextField();
        jTextField_soy = new javax.swing.JTextField();
        jTextField_email = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton_memekle = new javax.swing.JButton();
        jLabel_path = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton_resims = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel__.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel_mem_tit.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel_mem_tit.setForeground(new java.awt.Color(0, 0, 153));
        jLabel_mem_tit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_mem_tit.setText("ÜYE EKLEME");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel_mem_tit, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_mem_tit)
                .addContainerGap())
        );

        jLabel_adi.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        jLabel_adi.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_adi.setText("ADI:");

        jLabel_adih.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_adih.setText("*ADI GIRIN");

        jLabel4.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("TELEFON NO:");

        jLabel5.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("SOYADI:");

        jLabel6.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("EMAIL GIRIN:");

        jLabel_teleh.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_teleh.setText("*TELEFON GIRIN");

        jLabel_soyh.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_soyh.setText("*SOYADI GIRIN");

        jLabel_emailh.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_emailh.setText("*EMAIL GIRIN");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ERKEK", "KADIN" }));

        jButton_memekle.setText("EKLE");
        jButton_memekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_memekleActionPerformed(evt);
            }
        });

        jLabel_path.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        jLabel_path.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_path.setText("PROFİL RESİMİNİ SEÇİN");

        jLabel12.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("CİNSİYET");

        jButton_resims.setText("SEÇ");
        jButton_resims.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resimsActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(153, 204, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("X");
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel__Layout = new javax.swing.GroupLayout(jPanel__);
        jPanel__.setLayout(jPanel__Layout);
        jPanel__Layout.setHorizontalGroup(
            jPanel__Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel__Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel__Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel__Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel__Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_emailh, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel__Layout.createSequentialGroup()
                        .addGroup(jPanel__Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_tele, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel__Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel__Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_teleh, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_adih, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel__Layout.createSequentialGroup()
                                        .addComponent(jTextField_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62)
                                        .addComponent(jLabel_path, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel__Layout.createSequentialGroup()
                        .addGroup(jPanel__Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_soyh, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel__Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel__Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jTextField_soy, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_resims, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))))
            .addGroup(jPanel__Layout.createSequentialGroup()
                .addGroup(jPanel__Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel__Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel__Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jButton_memekle, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel__Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
        );
        jPanel__Layout.setVerticalGroup(
            jPanel__Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel__Layout.createSequentialGroup()
                .addGroup(jPanel__Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_adi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel__Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_path))
                .addGap(8, 8, 8)
                .addComponent(jLabel_adih)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel__Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButton_resims, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_soy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_soyh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_tele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel_teleh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_emailh)
                .addGap(23, 23, 23)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton_memekle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel__, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel__, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_resimsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resimsActionPerformed
        
		JFileChooser filechooser = new JFileChooser();
		filechooser.setDialogTitle("Dosya yada fofo secin");
		
		filechooser.setCurrentDirectory(new File("C:\\Users\\Hassan\\Pictures"));
		
		FileNameExtensionFilter fxf = new FileNameExtensionFilter("image",".png",".jpg","jepg");
		
		filechooser.addChoosableFileFilter(fxf);
		
		int filestate = filechooser.showSaveDialog(null);
		
		if(filestate ==JFileChooser.APPROVE_OPTION)
		{
			String path = filechooser.getSelectedFile().getAbsolutePath();
			jLabel_path.setText(path);
			
			imagePath = path;
		}
		
    }//GEN-LAST:event_jButton_resimsActionPerformed

    private void jButton_memekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_memekleActionPerformed
        // TODO add your handling code here:
		
		String fname = jTextField_adi.getText();
		String lname = jTextField_soy.getText();
		String phone = jTextField_tele.getText();
		String email = jTextField_email.getText();
		String gender = jComboBox1.getSelectedItem().toString();
		
		if(fname.isEmpty())
		{
		jLabel_adih.setVisible(true);
		}
		else if(lname.isEmpty())
		{
		jLabel_soyh.setVisible(true);
		}
		else if(phone.isEmpty())
		{
			jLabel_teleh.setVisible(true);
		}
		else{
		
		byte[] img=null;	
		
		
		if(imagePath!=null){
		
			
			try {
				
				Path path = Paths.get(imagePath);
				img = Files.readAllBytes(path);
				
				mem.addmember(fname, lname, phone, email, gender, img);
			} catch (IOException ex) {
				Logger.getLogger(AddMemberForm.class.getName()).log(Level.SEVERE, null, ex);
			}
			
			
		}else
		{
			JOptionPane.showMessageDialog(null,"not added","",1);
		}
		}
			
		
		
    }//GEN-LAST:event_jButton_memekleActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AddMemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AddMemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AddMemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AddMemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AddMemberForm().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_memekle;
    private javax.swing.JButton jButton_resims;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_adi;
    private javax.swing.JLabel jLabel_adih;
    private javax.swing.JLabel jLabel_emailh;
    private javax.swing.JLabel jLabel_mem_tit;
    private javax.swing.JLabel jLabel_path;
    private javax.swing.JLabel jLabel_soyh;
    private javax.swing.JLabel jLabel_teleh;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel__;
    private javax.swing.JTextField jTextField_adi;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_soy;
    private javax.swing.JTextField jTextField_tele;
    // End of variables declaration//GEN-END:variables
}
