/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



import MY_Classes.Func_Class;
import java.awt.Color;
import javax.swing.*;
import javax.swing.border.Border;


/**
 *
 * @author Hassan
 */


public class DashboardForm extends javax.swing.JFrame {
	MY_Classes.Func_Class func = new Func_Class();
		JLabel[] label = new JLabel[5];
		MY_Classes.Book book = new MY_Classes.Book();
	
	 Border button1 = BorderFactory.createMatteBorder(1,1,1, 1, Color.yellow);
	 Border button2 = BorderFactory.createMatteBorder(1,1,1, 1, new Color(34,40,49));
	public DashboardForm() {
		initComponents();
		displaycount();
		func.displayImage(jLabel_dash.getWidth(),jLabel_dash.getHeight(),null,"/My_Images/Logophoto.png", jLabel_dash);
		this.setLocationRelativeTo(null);
		
		func.displayImage(jLabel_dash.getWidth(),jLabel_dash.getHeight(),null,"/My_Images/Logophoto.png", jLabel_dash);
		
		label[0]= jLabel_image1;
		label[1]= jLabel_image2;
		label[2]= jLabel_image3;
		label[3]= jLabel_image3;
		label[4]= jLabel_image3;
		
		book.displaybookcovers(label);
		
	}
	public void displaycount()
	{

		yazanlarcount.setText(String.valueOf(func.Countdata("authors")));
		uyullarcount.setText(String.valueOf(func.Countdata("members")));
		jLabelkitapcount.setText(String.valueOf(func.Countdata("books")));
			
	}
		
		
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_dash = new javax.swing.JPanel();
        jPanel_menu = new javax.swing.JPanel();
        jPanel_sash = new javax.swing.JPanel();
        jLabel_dash = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton_yazaryon = new javax.swing.JButton();
        jButton_turyon = new javax.swing.JButton();
        jButton_ekle = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton_gor = new javax.swing.JButton();
        jButton_duz = new javax.swing.JButton();
        jButton_sil = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton_gor1 = new javax.swing.JButton();
        jButton_gor2 = new javax.swing.JButton();
        jButton_gor3 = new javax.swing.JButton();
        jButton_gor4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton_gor5 = new javax.swing.JButton();
        jButton_gor6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabelkitapcount = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        yazanlarcount = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        uyullarcount = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel_image3 = new javax.swing.JLabel();
        jLabel_image2 = new javax.swing.JLabel();
        jLabel_image1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel_dash.setBackground(new java.awt.Color(55, 58, 64));

        jPanel_menu.setBackground(new java.awt.Color(104, 109, 118));

        jPanel_sash.setBackground(new java.awt.Color(55, 58, 64));

        jLabel_dash.setBackground(new java.awt.Color(55, 58, 64));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(221, 221, 221));
        jLabel2.setText("Kütüphane");

        javax.swing.GroupLayout jPanel_sashLayout = new javax.swing.GroupLayout(jPanel_sash);
        jPanel_sash.setLayout(jPanel_sashLayout);
        jPanel_sashLayout.setHorizontalGroup(
            jPanel_sashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sashLayout.createSequentialGroup()
                .addComponent(jLabel_dash, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel_sashLayout.setVerticalGroup(
            jPanel_sashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_dash, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel_sashLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2))
        );

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(201, 44, 109));
        jLabel3.setText("KITAPLAR");

        jButton_yazaryon.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jButton_yazaryon.setForeground(new java.awt.Color(1, 32, 78));
        jButton_yazaryon.setText("YAZAR YÖNETIMI");
        jButton_yazaryon.setContentAreaFilled(false);
        jButton_yazaryon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_yazaryonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_yazaryonMouseExited(evt);
            }
        });
        jButton_yazaryon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_yazaryonActionPerformed(evt);
            }
        });

        jButton_turyon.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jButton_turyon.setForeground(new java.awt.Color(32, 38, 46));
        jButton_turyon.setText("TÜRLER YÖNETIMIİ");
        jButton_turyon.setContentAreaFilled(false);
        jButton_turyon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_turyonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_turyonMouseExited(evt);
            }
        });
        jButton_turyon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_turyonActionPerformed(evt);
            }
        });

        jButton_ekle.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jButton_ekle.setForeground(new java.awt.Color(1, 32, 78));
        jButton_ekle.setText("ÜYE EKLE");
        jButton_ekle.setContentAreaFilled(false);
        jButton_ekle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_ekleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_ekleMouseExited(evt);
            }
        });
        jButton_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ekleActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(244, 206, 20));
        jLabel12.setText("TÜRLER");

        jLabel13.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(235, 100, 64));
        jLabel13.setText("YAZARLAR");

        jButton_gor.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jButton_gor.setForeground(new java.awt.Color(1, 32, 78));
        jButton_gor.setText("KITAP EKLE");
        jButton_gor.setContentAreaFilled(false);
        jButton_gor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_gorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_gorMouseExited(evt);
            }
        });
        jButton_gor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_gorActionPerformed(evt);
            }
        });

        jButton_duz.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jButton_duz.setForeground(new java.awt.Color(1, 32, 78));
        jButton_duz.setText("ÜYE DÜZENLE");
        jButton_duz.setContentAreaFilled(false);
        jButton_duz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_duzMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_duzMouseExited(evt);
            }
        });
        jButton_duz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_duzActionPerformed(evt);
            }
        });

        jButton_sil.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jButton_sil.setForeground(new java.awt.Color(1, 32, 78));
        jButton_sil.setText("ÜYE SIL");
        jButton_sil.setContentAreaFilled(false);
        jButton_sil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_silMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_silMouseExited(evt);
            }
        });
        jButton_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_silActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(25, 167, 206));
        jLabel14.setText("ÜYELER");

        jButton_gor1.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jButton_gor1.setForeground(new java.awt.Color(1, 32, 78));
        jButton_gor1.setText("ÜYELERİ LISTESI");
        jButton_gor1.setContentAreaFilled(false);
        jButton_gor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_gor1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_gor1MouseExited(evt);
            }
        });
        jButton_gor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_gor1ActionPerformed(evt);
            }
        });

        jButton_gor2.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jButton_gor2.setForeground(new java.awt.Color(1, 32, 78));
        jButton_gor2.setText("KITAP SILME");
        jButton_gor2.setContentAreaFilled(false);
        jButton_gor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_gor2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_gor2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_gor2MouseExited(evt);
            }
        });
        jButton_gor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_gor2ActionPerformed(evt);
            }
        });

        jButton_gor3.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jButton_gor3.setForeground(new java.awt.Color(1, 32, 78));
        jButton_gor3.setText("KITAP LISTESI");
        jButton_gor3.setContentAreaFilled(false);
        jButton_gor3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_gor3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_gor3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_gor3MouseExited(evt);
            }
        });
        jButton_gor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_gor3ActionPerformed(evt);
            }
        });

        jButton_gor4.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jButton_gor4.setForeground(new java.awt.Color(1, 32, 78));
        jButton_gor4.setText("KITAP DUZENLE");
        jButton_gor4.setContentAreaFilled(false);
        jButton_gor4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_gor4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_gor4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_gor4MouseExited(evt);
            }
        });
        jButton_gor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_gor4ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(6, 208, 1));
        jLabel4.setText("KITAPLAR ODUÇ ALMAK");

        jButton_gor5.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jButton_gor5.setForeground(new java.awt.Color(1, 32, 78));
        jButton_gor5.setText("ODUNÇ ALMAK");
        jButton_gor5.setContentAreaFilled(false);
        jButton_gor5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_gor5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_gor5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_gor5MouseExited(evt);
            }
        });
        jButton_gor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_gor5ActionPerformed(evt);
            }
        });

        jButton_gor6.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jButton_gor6.setForeground(new java.awt.Color(1, 32, 78));
        jButton_gor6.setText("ODUNÇ IADE ET");
        jButton_gor6.setContentAreaFilled(false);
        jButton_gor6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_gor6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_gor6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_gor6MouseExited(evt);
            }
        });
        jButton_gor6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_gor6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_menuLayout = new javax.swing.GroupLayout(jPanel_menu);
        jPanel_menu.setLayout(jPanel_menuLayout);
        jPanel_menuLayout.setHorizontalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_sash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(jPanel_menuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_yazaryon)
                            .addComponent(jButton_turyon)
                            .addComponent(jButton_duz)
                            .addComponent(jButton_ekle)
                            .addComponent(jButton_sil)
                            .addComponent(jButton_gor1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_gor4)
                            .addComponent(jButton_gor)
                            .addComponent(jButton_gor2)
                            .addComponent(jButton_gor3)
                            .addComponent(jButton_gor6)
                            .addComponent(jButton_gor5)))))
        );
        jPanel_menuLayout.setVerticalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menuLayout.createSequentialGroup()
                .addComponent(jPanel_sash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_turyon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_yazaryon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_ekle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_duz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_sil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_gor1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_gor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_gor4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_gor2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_gor3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_gor5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_gor6)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(220, 95, 0));

        jLabelkitapcount.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabelkitapcount.setForeground(new java.awt.Color(0, 0, 0));
        jLabelkitapcount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelkitapcount.setText("test");

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Kitaplar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelkitapcount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabelkitapcount)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(244, 206, 20));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Yazarlar");

        yazanlarcount.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        yazanlarcount.setForeground(new java.awt.Color(0, 0, 0));
        yazanlarcount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yazanlarcount.setText("test");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(73, 73, 73))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(yazanlarcount, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(yazanlarcount)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(71, 147, 175));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("ÜYELER");

        uyullarcount.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        uyullarcount.setForeground(new java.awt.Color(0, 0, 0));
        uyullarcount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uyullarcount.setText("test");
        uyullarcount.setToolTipText("");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel5))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(uyullarcount, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(uyullarcount)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(118, 171, 174));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("EN SON EKLENEN KITAPLAR");

        jLabel_image3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_image3.setText("test");
        jLabel_image3.setOpaque(true);

        jLabel_image2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_image2.setText("test");
        jLabel_image2.setOpaque(true);

        jLabel_image1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_image1.setText("test");
        jLabel_image1.setOpaque(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel_image1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_image2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_image3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(383, 383, 383))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_image1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_image2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_image3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_dashLayout = new javax.swing.GroupLayout(jPanel_dash);
        jPanel_dash.setLayout(jPanel_dashLayout);
        jPanel_dashLayout.setHorizontalGroup(
            jPanel_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_dashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_dashLayout.createSequentialGroup()
                        .addGroup(jPanel_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_dashLayout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))))
        );
        jPanel_dashLayout.setVerticalGroup(
            jPanel_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_dashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel_dashLayout.createSequentialGroup()
                .addGroup(jPanel_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_dashLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_dash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_dash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_gor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_gor4ActionPerformed
        // TODO add your handling code here:
        EditBook editbook = new EditBook();
        editbook.setVisible(true);
    }//GEN-LAST:event_jButton_gor4ActionPerformed

    private void jButton_gor4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gor4MouseExited
        // TODO add your handling code here:
		this.setForeground(new Color(1,32,78));
    }//GEN-LAST:event_jButton_gor4MouseExited

    private void jButton_gor4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gor4MouseEntered
        // TODO add your handling code here:
		 jButton_sil.setForeground(Color.white);
    }//GEN-LAST:event_jButton_gor4MouseEntered

    private void jButton_gor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_gor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_gor3ActionPerformed

    private void jButton_gor3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gor3MouseExited
        // TODO add your handling code here:
		this.setForeground(new Color(1,32,78));
    }//GEN-LAST:event_jButton_gor3MouseExited

    private void jButton_gor3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gor3MouseEntered
        // TODO add your handling code here:
		 jButton_sil.setForeground(Color.white);
    }//GEN-LAST:event_jButton_gor3MouseEntered

    private void jButton_gor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_gor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_gor2ActionPerformed

    private void jButton_gor2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gor2MouseExited
        // TODO add your handling code here:
		this.setForeground(new Color(1,32,78));
    }//GEN-LAST:event_jButton_gor2MouseExited

    private void jButton_gor2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gor2MouseEntered
        // TODO add your handling code here:
		 jButton_sil.setForeground(Color.white);
    }//GEN-LAST:event_jButton_gor2MouseEntered

    private void jButton_gor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_gor1ActionPerformed
        // TODO add your handling code here:
        AuthorsListForm authorsform = new AuthorsListForm();
        authorsform.setVisible(true);
    }//GEN-LAST:event_jButton_gor1ActionPerformed

    private void jButton_gor1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gor1MouseExited
        // TODO add your handling code here:
		this.setForeground(new Color(1,32,78));
    }//GEN-LAST:event_jButton_gor1MouseExited

    private void jButton_gor1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gor1MouseEntered
        // TODO add your handling code here:
		 jButton_sil.setForeground(Color.white);
    }//GEN-LAST:event_jButton_gor1MouseEntered

    private void jButton_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_silActionPerformed
        // TODO add your handling code here:
        DeleteMemberForm deleteform = new DeleteMemberForm();
        deleteform.setVisible(true);
    }//GEN-LAST:event_jButton_silActionPerformed

    private void jButton_silMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_silMouseExited
        // TODO add your handling code here:
        jButton_sil.setForeground(new Color(1,32,78));
    }//GEN-LAST:event_jButton_silMouseExited

    private void jButton_silMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_silMouseEntered
        // TODO add your handling code here:
        jButton_sil.setForeground(Color.white);
    }//GEN-LAST:event_jButton_silMouseEntered

    private void jButton_duzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_duzActionPerformed
        // TODO add your handling code here:
        EditMemberForm editform = new EditMemberForm();
        editform.setVisible(true);
    }//GEN-LAST:event_jButton_duzActionPerformed

    private void jButton_duzMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_duzMouseExited
        // TODO add your handling code here:
        jButton_duz.setForeground(new Color(11,32,78));
    }//GEN-LAST:event_jButton_duzMouseExited

    private void jButton_duzMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_duzMouseEntered
        // TODO add your handling code here:

        jButton_duz.setForeground(Color.white);
    }//GEN-LAST:event_jButton_duzMouseEntered

    private void jButton_gorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_gorActionPerformed
        // TODO add your handling code here:
        AddBook adbook = new AddBook();
        adbook.setVisible(true);

    }//GEN-LAST:event_jButton_gorActionPerformed

    private void jButton_gorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gorMouseExited
        // TODO add your handling code here:
        jButton_gor.setForeground(new Color(1,32,78));
    }//GEN-LAST:event_jButton_gorMouseExited

    private void jButton_gorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gorMouseEntered
        // TODO add your handling code here:
        jButton_gor.setForeground(Color.white);
    }//GEN-LAST:event_jButton_gorMouseEntered

    private void jButton_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ekleActionPerformed
        // TODO add your handling code here:
        AddMemberForm addform = new AddMemberForm();
        addform.setVisible(true);

    }//GEN-LAST:event_jButton_ekleActionPerformed

    private void jButton_ekleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ekleMouseExited
        // TODO add your handling code here:
        jButton_ekle.setForeground(new Color(1,32,78));
    }//GEN-LAST:event_jButton_ekleMouseExited

    private void jButton_ekleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ekleMouseEntered
        // TODO add your handling code here:
        jButton_ekle.setForeground(Color.white);
    }//GEN-LAST:event_jButton_ekleMouseEntered

    private void jButton_turyonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_turyonActionPerformed
        ManageGenresForm formgen = new ManageGenresForm();
        formgen.setVisible(true);

    }//GEN-LAST:event_jButton_turyonActionPerformed

    private void jButton_turyonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_turyonMouseExited
        // TODO add your handling code here:
        jButton_turyon.setForeground(new Color(1,32,78));
    }//GEN-LAST:event_jButton_turyonMouseExited

    private void jButton_turyonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_turyonMouseEntered
        // TODO add your handling code here:
        jButton_turyon.setForeground(Color.white);
    }//GEN-LAST:event_jButton_turyonMouseEntered

    private void jButton_yazaryonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_yazaryonActionPerformed
        // TODO add your handling code here:
        ManageAuthorsForm formauth = new ManageAuthorsForm();
        formauth.setVisible(true);
    }//GEN-LAST:event_jButton_yazaryonActionPerformed

    private void jButton_yazaryonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_yazaryonMouseExited
        // TODO add your handling code here:
        jButton_yazaryon.setForeground(new Color(1,32,78));
    }//GEN-LAST:event_jButton_yazaryonMouseExited

    private void jButton_yazaryonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_yazaryonMouseEntered
        // TODO add your handling code here:
        jButton_yazaryon.setForeground(Color.white);
    }//GEN-LAST:event_jButton_yazaryonMouseEntered

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton_gor5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gor5MouseEntered
        // TODO add your handling code here:
		 jButton_sil.setForeground(Color.white);
    }//GEN-LAST:event_jButton_gor5MouseEntered

    private void jButton_gor5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gor5MouseExited
        // TODO add your handling code here:
		this.setForeground(new Color(1,32,78));
    }//GEN-LAST:event_jButton_gor5MouseExited

    private void jButton_gor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_gor5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_gor5ActionPerformed

    private void jButton_gor6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gor6MouseEntered
        // TODO add your handling code here:
		 jButton_sil.setForeground(Color.white);
    }//GEN-LAST:event_jButton_gor6MouseEntered

    private void jButton_gor6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gor6MouseExited
        // TODO add your handling code here:
		this.setForeground(new Color(1,32,78));
    }//GEN-LAST:event_jButton_gor6MouseExited

    private void jButton_gor6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_gor6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_gor6ActionPerformed

    private void jButton_gor4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gor4MouseClicked
        // TODO add your handling code here:
	EditBook e = new EditBook();
	e.setVisible(true);
		
    }//GEN-LAST:event_jButton_gor4MouseClicked

    private void jButton_gor2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gor2MouseClicked
        // TODO add your handling code here:
		deletebook d = new deletebook();
		d.setVisible(true);
    }//GEN-LAST:event_jButton_gor2MouseClicked

    private void jButton_gor3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gor3MouseClicked
        // TODO add your handling code here:
		BooksList l = new BooksList();
		l.setVisible(true);
    }//GEN-LAST:event_jButton_gor3MouseClicked

    private void jButton_gor5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gor5MouseClicked
        // TODO add your handling code here:
		IssueBookForm i = new IssueBookForm();
		 i.setVisible(true);
    }//GEN-LAST:event_jButton_gor5MouseClicked

    private void jButton_gor6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gor6MouseClicked
        // TODO add your handling code here:
		ReturnBookForm f = new ReturnBookForm();
		f.setVisible(true);
    }//GEN-LAST:event_jButton_gor6MouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new DashboardForm().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_duz;
    private javax.swing.JButton jButton_ekle;
    private javax.swing.JButton jButton_gor;
    private javax.swing.JButton jButton_gor1;
    private javax.swing.JButton jButton_gor2;
    private javax.swing.JButton jButton_gor3;
    private javax.swing.JButton jButton_gor4;
    private javax.swing.JButton jButton_gor5;
    private javax.swing.JButton jButton_gor6;
    private javax.swing.JButton jButton_sil;
    private javax.swing.JButton jButton_turyon;
    private javax.swing.JButton jButton_yazaryon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_dash;
    private javax.swing.JLabel jLabel_image1;
    private javax.swing.JLabel jLabel_image2;
    private javax.swing.JLabel jLabel_image3;
    private javax.swing.JLabel jLabelkitapcount;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel_dash;
    private javax.swing.JPanel jPanel_menu;
    private javax.swing.JPanel jPanel_sash;
    private javax.swing.JLabel uyullarcount;
    private javax.swing.JLabel yazanlarcount;
    // End of variables declaration//GEN-END:variables
}
