
import MY_Classes.Func_Class;
import java.awt.Color;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Hassan
 */
public class ManageGenresForm extends javax.swing.JFrame {
		MY_Classes.Func_Class func = new Func_Class();
	/**
	 * Creates new form ManageGenresForm
	 */
	public ManageGenresForm() {
		initComponents();

		this.setLocationRelativeTo(null);

		Border panelHeaderBorder  = BorderFactory.createMatteBorder(5,5,5,5,new Color(102,102,102));
		jPanel1.setBorder(panelHeaderBorder);

		func.displayImage(75,50,null,"/My_Images/hire.png", jLabel1_FormTitle);

		jTable_Genres_.setSelectionBackground(Color.lightGray);
		jTable_Genres_.setRowHeight(30);
		jTable_Genres_.setShowGrid(true);
		//jLabel3.setVisible(false);
		populateJtableWithGenres();
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1_FormTitle = new javax.swing.JLabel();
        jLabel1_CloseForm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jTextField_Namw = new javax.swing.JTextField();
        jButton_add_ = new javax.swing.JButton();
        jButton_delete_ = new javax.swing.JButton();
        jButton_edit_ = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Genres_ = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1_FormTitle.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1_FormTitle.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1_FormTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_FormTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_FormTitle.setText("TÜRLER YÖNETIMIİ");
        jLabel1_FormTitle.setOpaque(true);

        jLabel1_CloseForm.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1_CloseForm.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1_CloseForm.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_CloseForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_CloseForm.setText("X");
        jLabel1_CloseForm.setOpaque(true);
        jLabel1_CloseForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_CloseFormMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("     ADI:");

        jLabel2.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText(" NO:");

        jTextField_Namw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NamwActionPerformed(evt);
            }
        });

        jButton_add_.setText("TÜR EKLE +");
        jButton_add_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_ActionPerformed(evt);
            }
        });

        jButton_delete_.setText("TÜR SIL -");
        jButton_delete_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_delete_ActionPerformed(evt);
            }
        });

        jButton_edit_.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton_edit_.setText("TÜR DÜZENLE %");
        jButton_edit_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_edit_ActionPerformed(evt);
            }
        });

        jTable_Genres_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Genres_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Genres_MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Genres_);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("*TÜR NO VE ADI GIRIN");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1_FormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1_CloseForm, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Namw, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_add_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_edit_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_delete_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1_CloseForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1_FormTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Namw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_add_, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_edit_, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_delete_, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_NamwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NamwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NamwActionPerformed

    private void jButton_add_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_ActionPerformed
        // TODO add your handling code here:
		MY_Classes.Genre gen = new MY_Classes.Genre();
		String name = jTextField_Namw.getText();
		if(name.isEmpty()){
			//JOptionPane.showMessageDialog(null,"name section is empty","",0);
			jLabel3.setVisible(true);
		}else
			gen.addGenre(name);
		populateJtableWithGenres();
    }//GEN-LAST:event_jButton_add_ActionPerformed

    private void jButton_delete_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_delete_ActionPerformed
        // TODO add your handling code here:
		MY_Classes.Genre gen = new MY_Classes.Genre();
		try{
			int id = Integer.valueOf(jTextField_ID.getText());
			gen.deleteGenre(id);
		}catch(NumberFormatException ex)
		{
			JOptionPane.showMessageDialog(null,"Invalid ID"+ex.getMessage(),"",2);
		}
		populateJtableWithGenres();
    }//GEN-LAST:event_jButton_delete_ActionPerformed

    private void jButton_edit_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_edit_ActionPerformed
        // TODO add your handling code here:

		String name = jTextField_Namw.getText();
		MY_Classes.Genre gen = new MY_Classes.Genre();

		if(name.isEmpty()){
			//JOptionPane.showMessageDialog(null,"name section is empty","",0);
			jLabel3.setVisible(true);
		}else
		try{
			int id = Integer.valueOf(jTextField_ID.getText());
			gen.editGenre(id, name);
		}catch(NumberFormatException ex)
		{
			JOptionPane.showMessageDialog(null,"Invalid ID"+ex.getMessage(),"",2);
		}
		populateJtableWithGenres();
    }//GEN-LAST:event_jButton_edit_ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
		jLabel3.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jTable_Genres_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Genres_MouseClicked
        // TODO add your handling code here:
		int index = jTable_Genres_.getSelectedRow();
		
		String id = jTable_Genres_.getValueAt(index,0).toString();
		String name = jTable_Genres_.getValueAt(index,1).toString();
		
		jTextField_ID.setText(id);
		jTextField_Namw.setText(name);
    }//GEN-LAST:event_jTable_Genres_MouseClicked

    private void jLabel1_CloseFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_CloseFormMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1_CloseFormMouseClicked
	public void populateJtableWithGenres()
	{
		MY_Classes.Genre gen = new MY_Classes.Genre();
		ArrayList<MY_Classes.Genre> genresList = gen.genreList();
		
		String[] colNames = {"NO","ISIM"};

		Object[][] rows = new Object[genresList.size()][colNames.length];
		
		for(int i =0;i <genresList.size();i++)
		{
			rows[i][0] = genresList.get(i).getId();
			rows[i][1] = genresList.get(i).getName();
		}
		DefaultTableModel model = new DefaultTableModel(rows,colNames);
		jTable_Genres_.setModel(model);
		
	}
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
				//	javax.swing.UIManager.setLookAndFeel(info.getClassName());
					javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ManageGenresForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ManageGenresForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ManageGenresForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ManageGenresForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ManageGenresForm().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add_;
    private javax.swing.JButton jButton_delete_;
    private javax.swing.JButton jButton_edit_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_CloseForm;
    private javax.swing.JLabel jLabel1_FormTitle;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Genres_;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_Namw;
    // End of variables declaration//GEN-END:variables
}
