
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hassan
 */
public class MemberListForm extends javax.swing.JFrame {

	/**
	 * Creates new form MemberListForm
	 */
	MY_Classes.Func_Class func = new MY_Classes.Func_Class();
	MY_Classes.Members members = new MY_Classes.Members();
	
	public MemberListForm() {
		initComponents();
		populateJtableWithMembers("");
		
		this.setLocationRelativeTo(this);
		
		Border p = BorderFactory.createMatteBorder(5, 5,5,5, new Color(0,153,153));
		jPanel_.setBorder(p);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel_ = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_uye_del = new javax.swing.JTextField();
        jButton_uye_del = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_memlist = new javax.swing.JTable();
        jLabel_MEMADI = new javax.swing.JLabel();
        jLabel_MEMEM = new javax.swing.JLabel();
        jLabel_MEMCI = new javax.swing.JLabel();
        jLabel_MEMTELE = new javax.swing.JLabel();
        jLabel_p = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("üye NO:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ÜYE LISTESI");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("üye ARA:");

        jButton_uye_del.setText("ARA");
        jButton_uye_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_uye_delActionPerformed(evt);
            }
        });

        jTable_memlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_memlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_memlistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_memlist);

        jLabel_MEMADI.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel_MEMADI.setText("ADI");

        jLabel_MEMEM.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel_MEMEM.setText("EMAIL");

        jLabel_MEMCI.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel_MEMCI.setText("CINSIYET");

        jLabel_MEMTELE.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel_MEMTELE.setText("TELE NO");

        jLabel_p.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_p.setOpaque(true);

        javax.swing.GroupLayout jPanel_Layout = new javax.swing.GroupLayout(jPanel_);
        jPanel_.setLayout(jPanel_Layout);
        jPanel_Layout.setHorizontalGroup(
            jPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel_Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField_uye_del, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton_uye_del, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel_p, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(jPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_MEMTELE, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_MEMADI, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_MEMEM, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_MEMCI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22))))
        );
        jPanel_Layout.setVerticalGroup(
            jPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Layout.createSequentialGroup()
                .addGroup(jPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_uye_del, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_uye_del, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_Layout.createSequentialGroup()
                        .addComponent(jLabel_p, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel_MEMADI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_MEMTELE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_MEMEM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_MEMCI)))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_uye_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_uye_delActionPerformed
        // TODO add your handling code here:
		String value = jTextField_uye_del.getText();
		String query ="SELECT * FROM `members` WHERE `firstName` LIKE '%"+value+"%' OR`lastName`LIKE '%"+value+"%'";
		populateJtableWithMembers(query);
      
    }//GEN-LAST:event_jButton_uye_delActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
		this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTable_memlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_memlistMouseClicked
        // TODO add your handling code here:
		
		try {
			
		Integer RowIndex = jTable_memlist.getSelectedRow();
		Integer id = Integer.parseInt(jTable_memlist.getModel().getValueAt(RowIndex, 0).toString());
			
			//Members selectedmembers = (Members) members.getMemberById(id);
			MY_Classes.Members selectedmembers = (MY_Classes.Members) members.getMemberById(id);
			
			
			if(selectedmembers != null)
			{
			//jl.setText(String.valueOf(selectedmembers.getId()));
			jLabel_MEMADI.setText(selectedmembers.getFirstName()+selectedmembers.getLastName());
			jLabel_MEMTELE.setText(selectedmembers.getPhone());
			jLabel_MEMEM.setText(selectedmembers.getEmail());
			//jTextField_uye_foto.setText(selectedmembers.getPicture());
			jLabel_MEMCI.setText(selectedmembers.getGender());
			
			byte[] image = selectedmembers.getPicture();
			
			func.displayImage(jLabel_p.getWidth(), jLabel_p.getHeight(), image,"", jLabel_p);
			
			}else
			{
				JOptionPane.showMessageDialog(null, "BU IDYE SAHİP ÜYE BULUNAMADI","",1);
			}
			
		
		} catch (SQLException | NumberFormatException ex) {
			//Logger.getLogger(MemberEditForm.class.getName()).log(Level.SEVERE, null, ex);
		//	jLabel_uyenoh.setVisible(true);
		JOptionPane.showMessageDialog(null,"","",1);
			
		}
    }//GEN-LAST:event_jTable_memlistMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MemberListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MemberListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MemberListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MemberListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MemberListForm().setVisible(true);
			}
		});
	}
	public void populateJtableWithMembers(String query)
	{
		MY_Classes.Members aot = new MY_Classes.Members();
		
		ArrayList<MY_Classes.Members> memberList = aot.memberList(query);
		
		String[] colNames = {"NO","ADI", "SOY-ADI","TEL","EMAIL","CINSYET"};

		Object[][] rows = new Object[memberList.size()][colNames.length];
		
		for(int i =0;i <memberList.size();i++)
		{
			rows[i][0] = memberList.get(i).getId();
			rows[i][1] = memberList.get(i).getFirstName();
			rows[i][2] = memberList.get(i).getLastName();
			rows[i][3] = memberList.get(i).getPhone();
			rows[i][4] = memberList.get(i).getEmail();
			rows[i][5] = memberList.get(i).getGender();
	
			
			
		}
		DefaultTableModel model = new DefaultTableModel(rows,colNames);
		jTable_memlist.setModel(model);
		
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_uye_del;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_MEMADI;
    private javax.swing.JLabel jLabel_MEMCI;
    private javax.swing.JLabel jLabel_MEMEM;
    private javax.swing.JLabel jLabel_MEMTELE;
    private javax.swing.JLabel jLabel_p;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_memlist;
    private javax.swing.JTextField jTextField_uye_del;
    // End of variables declaration//GEN-END:variables
}
