
import MY_Classes.Book;
import MY_Classes.DB;
import MY_Classes.Func_Class;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hassan
 */
public class OGRENCIDASHBOARD extends javax.swing.JFrame {

	
	JLabel[] label = new JLabel[5];
	MY_Classes.Book book = new Book();
	public OGRENCIDASHBOARD() {
		initComponents();
		this.setLocationRelativeTo(this);
		
		label[0]= jLabel_image1;
		label[1]= jLabel_image2;
		label[2]= jLabel_image3;
		label[3]= jLabel_image3;
		label[4]= jLabel_image3;
		
		book.displaybookcovers(label);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlabelmerhaba = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel_image3 = new javax.swing.JLabel();
        jLabel_image2 = new javax.swing.JLabel();
        jLabel_image1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton_gor6 = new javax.swing.JButton();
        jButton_gor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(55, 58, 64));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jlabelmerhaba.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jlabelmerhaba.setText("merhabalar");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("x");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jlabelmerhaba, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelmerhaba, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel6.setBackground(new java.awt.Color(118, 171, 174));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("EN YENI GELEN KITAPLAR");

        jLabel_image3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_image3.setText("test");
        jLabel_image3.setOpaque(true);

        jLabel_image2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_image2.setText("test");
        jLabel_image2.setOpaque(true);

        jLabel_image1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_image1.setText("test");
        jLabel_image1.setOpaque(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_image1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_image2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_image3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(383, 383, 383))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_image1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_image2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_image3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(104, 109, 118));

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(6, 208, 1));
        jLabel4.setText("KITAPLAR ODUÇ ALMAK");

        jButton_gor6.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jButton_gor6.setForeground(new java.awt.Color(1, 32, 78));
        jButton_gor6.setText("ODUNÇ IADE ET");
        jButton_gor6.setContentAreaFilled(false);
        jButton_gor6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_gor6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_gor6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_gor6MouseExited(evt);
            }
        });
        jButton_gor6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_gor6ActionPerformed(evt);
            }
        });

        jButton_gor.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jButton_gor.setForeground(new java.awt.Color(1, 32, 78));
        jButton_gor.setText("ODUNÇ ALMAK");
        jButton_gor.setContentAreaFilled(false);
        jButton_gor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_gorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_gorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_gorMouseExited(evt);
            }
        });
        jButton_gor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_gorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jButton_gor6)
                    .addComponent(jButton_gor))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_gor6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_gor)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	public void displaybookcovers(JLabel[] label)
	{
		
		
		
	    ResultSet rs;
		java.sql.Statement st;
		int i = 0;
		MY_Classes.Func_Class func = new Func_Class();
		try { 
			 st = DB.getConnection().createStatement();
			 rs =st.executeQuery("SELECT `cover_image` FROM `books` LIMIT 5");
			 byte[] image;
			 while(rs.next())
			{
			image = rs.getBytes("cover_image");
			func.displayImage(label[i].getWidth(),label[i].getHeight(), image, "", label[i]);
			i++;
			
			}
		} catch (SQLException ex) {
			Logger.getLogger(Func_Class.class.getName()).log(Level.SEVERE, null, ex);
		}
	
		
		
	}

    private void jButton_gor6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gor6MouseClicked
        // TODO add your handling code here:
        ReturnBookForm f = new ReturnBookForm();
        f.setVisible(true);
    }//GEN-LAST:event_jButton_gor6MouseClicked

    private void jButton_gor6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gor6MouseEntered
        // TODO add your handling code here:
        jlabelmerhaba.setForeground(Color.white);
    }//GEN-LAST:event_jButton_gor6MouseEntered

    private void jButton_gor6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gor6MouseExited
        // TODO add your handling code here:
        this.setForeground(new Color(1,32,78));
    }//GEN-LAST:event_jButton_gor6MouseExited

    private void jButton_gor6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_gor6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_gor6ActionPerformed

    private void jButton_gorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gorMouseClicked
        // TODO add your handling code here:
        IssueBookForm i = new IssueBookForm();
        i.setVisible(true);
    }//GEN-LAST:event_jButton_gorMouseClicked

    private void jButton_gorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gorMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_gorMouseEntered

    private void jButton_gorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_gorMouseExited
        // TODO add your handling code here:
        this.setForeground(new Color(1,32,78));
    }//GEN-LAST:event_jButton_gorMouseExited

    private void jButton_gorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_gorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_gorActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
		this.dispose();
		LoginForm l = new LoginForm();
		l.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(OGRENCIDASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(OGRENCIDASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(OGRENCIDASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(OGRENCIDASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new OGRENCIDASHBOARD().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_gor;
    private javax.swing.JButton jButton_gor6;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_image1;
    private javax.swing.JLabel jLabel_image2;
    private javax.swing.JLabel jLabel_image3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel jlabelmerhaba;
    // End of variables declaration//GEN-END:variables
}
